config/routes.rb
Rails.application.routes.draw do
  root to: 'static#welcome'
  devise_for :users, controllers: { registrations: 'registrations' }
  get '/.well-known/stellar.toml' => 'static#stellar'
  get '/federation' => 'users#federation_search'
  get '/search' => 'users#search'
  get '/u/:id' => 'users#show', id: /.*/, as: 'user'
  resources :accounts, only: [:show, :destroy]
end

app/models/account.rb
require 'bcrypt'
require 'stellar-sdk'

class Account < ApplicationRecord
  self.primary_key = :public_key

  attr_encrypted :secret_key,
    key: Base64.decode64(Rails.application.secrets.encryption_key),
    algorithm: 'aes-256-cbc',
    mode: :single_iv_and_salt,
    insecure_mode: true,
    salt: Rails.application.secrets.salt

  after_create :start_watching
  after_destroy :stop_watching

  def start_watching
    StellarFed::Application::CACHE_CLIENT.hset(Account.cache_key, public_key, email)
  rescue => e
    logger.warn e
  end

  def stop_watching
    StellarFed::Application::CACHE_CLIENT.hdel(Account.cache_key, public_key)
  rescue => e
    logger.warn e
  end

  def self.update_watch
    watched_accounts = StellarFed::Application::CACHE_CLIENT.hkeys(Account.cache_key)
    watched_accounts.each do |k|
      StellarFed::Application::CACHE_CLIENT.hdel(Account.cache_key, k)
    end
    Account.find_each(&:start_watching)
  rescue => e
    logger.warn e
  end

  def self.find_or_create(email)
    key_pair = Stellar::KeyPair.random
    create_with(public_key: key_pair.address, secret_key: key_pair.seed)
      .find_or_create_by(email: email)
  end

  def hashed_address
    ::BCrypt::Engine.hash_secret(public_key, Rails.application.secrets.salt).to_s
  end

  def balance
    account = Stellar::Account.from_seed(secret_key)
    account_info = Rails.application.config.stellar_client.account_info(account)
    account_info.balances.find { |b| b['asset_type'] == 'native' }['balance']
  rescue => e
    logger.warn e
    return 0
  end

  private

  def self.cache_key
    Rails.application.secrets.new_account_cache_key
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
require 'barby'
require 'barby/barcode'
require 'barby/barcode/qr_code'
require 'barby/outputter/png_outputter'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  self.primary_key = :email
  validates :account_id, presence: true, allow_blank: false, length: { is: 56 }
  has_one_attached :avatar

  scope :confirmed, -> { where.not(confirmed_at: nil) }
  
  after_update_commit :update_cache
  after_destroy :uncache

  def self.get(email)
    user = where(email: email).first
    return user if user.present?

    account = Account.find_or_create(email)
    return User.new(
      email: email,
      account_id: account.public_key,
      confirmed_at: Time.now)
  end

  def self.update_cache
    confirmed.where(receive_email_notifications: true).find_each(&:cache)
  rescue => e
    logger.warn e
  end

  def stellar_address
    "#{self.email}*#{StellarFed::Application::DOMAIN}"
  end

  def account_id_qr_code
    barcode = Barby::QrCode.new(self.account_id, level: :q, size: 5)
    base64_output = Base64.encode64(barcode.to_png({ xdim: 5 }))
    "data:image/png;base64,#{base64_output}"
  end

  def after_confirmation
    super
    cache
  end

  def uncache
    StellarFed::Application::CACHE_CLIENT.srem(account_id, email)
  rescue => e
    logger.warn e
  end

  def cache
    if receive_email_notifications && confirmed?
      StellarFed::Application::CACHE_CLIENT.sadd(account_id, email)
    end
  rescue => e
    logger.warn e
  end

  private

  def update_cache
    receive_email_notifications ? cache : uncache
  end
end

app/controllers/accounts_controller.rb
require 'openssl'
require 'base64'

class AccountsController < ApplicationController
  before_action :set_account_and_token, only: [:show, :destroy]

  def show
    render :show and return
  end

  def destroy
    @account.destroy
    render @account, status: :ok, layout: false
  end

  private

  def set_account_and_token
    permitted_params = params.permit(:id, :token)
    @account = Account.find(permitted_params[:id])
    @token = permitted_params[:token]

    if @account.hashed_address != @token
      not_found
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(:email, :password, :account_id, :receive_email_notifications)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :current_password, :account_id, :avatar, :receive_email_notifications)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome
    if current_user.present?
      redirect_to user_path(current_user) and return
    end
  end

  def stellar
    response.headers['Access-Control-Allow-Origin'] = '*'
    render plain: "FEDERATION_SERVER = \"https://#{StellarFed::Application::DOMAIN}/federation\"" and return
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_search_query_and_type, only: [:federation_search]
  before_action :set_search_query, only: [:search]

  def show
    @user = User.confirmed.where(email: params[:id]).first
    render :show, status: @user.blank? ? :not_found : :ok and return
  end

  def search
    @user = User.confirmed.where("email = ? OR account_id = ?", @search_query, @search_query).first
    if @user.present?
      redirect_to user_path(@user) and return
    end
    render :show and return
  end

  def federation_search
    response.headers['Access-Control-Allow-Origin'] = '*'
    case @search_type
    when 'name'
      @user = User.get(@search_query)
    when 'id'
      @user = User.confirmed.where(account_id: @search_query).first
    else
      render status: :bad_request, json: { detail: "cannot handle '#{@search_type}' type" }.to_json and return
    end

    unless @user.confirmed?
      render status: :not_found, json: { detail: "no record found" }.to_json and return
    end

    resp = {
      stellar_address: @user.stellar_address,
      account_id: @user.account_id,
    }.merge(@memo.present? ? { memo: @memo, memo_type: 'text' } : {})

    render status: :ok, json: resp.to_json and return
  end

  private

  def set_search_query_and_type
    return unless set_search_query
    return unless set_search_type

    # Extract memo if present by looking for + after the before but before *
    # Example: john@email.com+memo*stellarfed.org
    if @search_type == 'name'
      matches = @search_query.scan(/^(.+@[^\+]+)\+?(.+)?/)
      if matches.blank?
        render status: :bad_request, json: { detail: "bad query" }.to_json and return
      end

      @search_query, @memo = matches.first
    end
  end

  def set_search_query
    if params[:q].blank?
      render status: :bad_request, json: { detail: "missing query" }.to_json and return
    end
    
    @search_query ||= params[:q].gsub(/\*#{Regexp.quote(StellarFed::Application::DOMAIN)}$/, '')
  end

  def set_search_type
    if params[:type].blank?
      render status: :bad_request, json: { detail: "missing type" }.to_json and return
    end

    @search_type ||= params[:type]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @user ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def donate_account
    User.where(email: StellarFed::Application::DONATION_ACCOUNT).first
  end

  def num_of_transactions_processed
    StellarFed::Application::CACHE_CLIENT.get('TRANSACTIONS_PROCESSED')
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/accounts/_account.html.erb
<p>
  Public Key:<br/>
  <code><%= @account.public_key %></code>
  <br/>
  Secret Key:<br/>
  <code><%= @account.secret_key %></code>
</p>
<p>
  Use the Secret key shown above to access or transfer lumens via the official Stellar.org
  <a target="_blank" href="https://www.stellar.org/account-viewer/#!/">Account Viewer Wallet</a>
</p>

app/views/accounts/show.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag "accounts" %>
<% end %>
<div class="side-image accounts">
  <div class="images-wrapper"></div>
  <div class="side-image-content">
    <div class="container">
      <p class="flash-error">
        <strong>ATTENTION:</strong>
        The Stellar Public and Secret key will be displayed one time only, after pressing the <code>Reveal Account Details</code> button below.
        <br/>
        Once your Public and Secret key is revealed, please write it down and keep it safe.
        <br/>
        You will lose access to your lumens if you lose your Secret key.
      </p>
      <h4>Stellar Account Details</h4>
      <h1>You have <%= @account.balance rescue 0 %> Stellar Lumens in your Stellar Account</h1>
      <button class="reveal">Reveal Account Details</button>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

    <title><%= content_for?(:title) ? yield(:title) : "Stellar Federation Service" %></title>
    <meta name="description" content="Stellar Fed - A Stellar Federation Service and an open source Federation Server" />
    <meta property="og:title" content="Stellar Fed - A Stellar Federation Service and an open source Federation Server" />
    <meta property="og:url" content="https://stellarfed.org" />
    <meta property="og:description" content="Free Stellar Federation Service with account watcher. Send lumens to your friend using just their email and StellarFed with create an account and email your friends with detail about the Stellar account." />
    <meta property="og:type" content="website" />

    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-113897981-1"></script>
    <script>function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","UA-113897981-1");</script>
  </head>

  <body>
    <%= render partial: "refills/navigation" %>
    <%= render partial: "refills/flashes" %>
    <main>
      <%= yield %>
    </main>
    <%= render partial: "refills/footer" %>
    <%= render partial: "static/jquery" %>
    <%= javascript_include_tag "application" %>
    <%= yield :javascripts %>
  </body>
</html>

app/views/refills/_device.html.erb
<div class="device-background">
  <div class="device-text">
    <h4>Easy to use</h4>
    <p>Send lumens using recognization Stellar Address instead of using Stellar Account ID. This will help give you some assurance that you are sending it to the right person. Supported by most wallets including Stellar's Account Viewer.</p>
  </div>
  <div class="device">
    <div class="screen"></div>
  </div>
</div>

app/views/refills/_flashes.html.erb
<% flash.each do |type, msg| %>
  <div class='flash-<%= "#{type}" %>'>
    <span><%= msg %></span>
  </div>
<% end %>

app/views/refills/_footer.html.erb
<footer class="footer" role="contentinfo">
  <div class="footer-logo">
    <p>StellarFed</p>
    <p>A Stellar Federation Service</p>
  </div>
  <hr />
  <div class="footer-links">
    <ul>
      <li><h3>Donate</h3></li>
      <li>
        <% cache donate_account do %>
          <code><%= link_to donate_account.stellar_address, user_path(donate_account) %></code>
        <% end %>
      </li>
    </ul>
  </div>
</footer>

app/views/refills/_icon_bullet_points.html.erb
<ul class="bullets">
  <li class="bullet">
    <div class="bullet-icon bullet-icon-1">
      <%= image_tag "planet.svg" %>
    </div>
    <div class="bullet-content">
      <h2>Federation Service</h2>
      <p>Provides Stellar Federation Service to lookup a Stellar Acount using a easy to remember email address.</p>
      </div>
  </li>  
  <li class="bullet">
    <div class="bullet-icon bullet-icon-2">
      <%= image_tag "notification.svg" %>
    </div>
    <div class="bullet-content">
      <h2>Email Notifications</h2>
      <p>
        Receive email notifications when someone sends you payment via the Stellar network to your Stellar Account.
        Processed <%= number_to_human(num_of_transactions_processed, precision: 3, significant: false) %> payment and account creation transactions on the Stellar Network to date.
      </p>
    </div>
  </li>
  <li class="bullet">
    <div class="bullet-icon bullet-icon-3">
      <%= image_tag "json.svg" %>
    </div>
    <div class="bullet-content">
      <h2>Compliant</h2>
      <p>The service is compliant with the Federation protocol defined by Stellar organization.</p>
    </div>
  </li>
  <li class="bullet">
    <div class="bullet-icon bullet-icon-4">
      <%= image_tag "email.svg" %>
    </div>
    <div class="bullet-content">
      <h2>Send Lumen using just Email</h2>
      <p>Send lumens to someone using their email even if they do not have an existing Stellar Account already.</p>
    </div>
  </li>
</ul>

app/views/refills/_navigation.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="/" class="logo">
      StellarFed
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <% if current_user.present? %>
          <li id="js-centered-more" class="nav-link more">
            <a href="javascript:void(0)">Profile</a>
            <ul class="submenu">
              <li>
                <%= link_to('Settings', edit_user_registration_path) %>
              </li>
              <li>
                <%= link_to('Sign Out', destroy_user_session_path, method: :delete) %>
              </li>
            </ul>
          </li>
        <% else %>
          <li id="js-centered-more" class="nav-link more">
            <a href="javascript:void(0)">Sign In</a>
            <ul class="submenu with-form">
              <li>
                <%= form_for(User.new, as: resource_name, url: session_path(resource_name), html: { id: "sign_in_user" }) do |f| %>
                  <%= f.label :email %>
                  <%= f.email_field :email, autofocus: true, autocomplete: "email", id: "sign_in_email" %>
                  <%= f.label :password %>
                  <%= f.password_field :password, autocomplete: "off", id: "sign_in_password" %>
                  <% if devise_mapping.rememberable? %>
                    <label>
                      <%= f.check_box :remember_me %> Remember me
                    </label>
                  <% end %>
                  <%= f.submit "Log in" %>
                <% end %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
    <div class="navigation-tools">
      <div class="search-bar">
        <form role="search" action="/search" method="GET">
          <input type="search" name="q" placeholder="Search by Stellar Address or Account ID" />
          <button type="submit">
            <%= image_tag "search.svg" %>
          </button>
        </form>
      </div>
    </div>
  </div>
</header>

app/views/users/_form.html.erb
<div class="side-image">
  <div class="images-wrapper"></div>
  <div class="side-image-content">
    <h4>Stellar Federation Service</h4>
    <h1>Create a Stellar Address</h1>
    <div class="row">
      <div class="container">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>
          <div class="row collapse combo-input">
            <%= f.label :email, "Your email address for the Stellar Address" %>
            <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "john@email.com" %>
            <span class="postfix">
              <span class="asterisk">*</span>
              <%= StellarFed::Application::DOMAIN %>
            </span>
          </div>

          <div class="row collapse">
            <%= f.label :password %>
            <%= f.password_field :password, autocomplete: "off", placeholder: "Password to change or delete Stellar address" %>
          </div>

          <div class="row collapse">
            <%= f.label :account_id, "Stellar Public Key" %>
            <%= f.text_field :account_id, autocomplete: "off", placeholder: "GD6WU64OEP5C4LRBH6NK3MHYIA2ADN6K6II6EXPNVUR3ERBXT4AN4ACD" %>
          </div>

          <div class="row collapse email-notifications">
            <%= f.check_box :receive_email_notifications %> <%= f.label :receive_email_notifications, "Receive email notifications for incoming payments to this Stellar account" %>
          </div>

          <div class="row collapse">
            <%= f.submit "Create Stellar Address", class: "button round" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if @user.present? %>
  <% content_for :title, "#{@user.email} - Stellar Federation Address" %>
<% end %>
<div class="side-image">
  <div class="images-wrapper">
    <% if @user.present? %>
      <%= image_tag @user.account_id_qr_code, alt: "Account ID", class: "qr-code" %>
    <% end %>
  </div>
  <div class="side-image-content">
    <% if @user.present? %>
      <h4>Stellar Address</h4>
      <h1><code><%= @user.stellar_address %></code></h1>
      <p><code><%= @user.account_id %></code></p>
    <% else %>
      <h1>Stellar Address Not Found 🙁</h1>
      <p>Check if Account ID or Stellar Address is correct.</p>
    <% end %>
  </div>
</div>